language: node_js
node_js: 8
services:
- docker
cache:
  directories:
  - node_modules
  - "$HOME/gcloud"
env:
- PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin
before_install:
- cd $TRAVIS_BUILD_DIR
- openssl aes-256-cbc -K $encrypted_1a9b5f4c6fc9_key -iv $encrypted_1a9b5f4c6fc9_iv -in client_credentials.json.enc -out client_credentials.json -d
- if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then 
    mkdir -p $HOME/gcloud && 
    wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud && 
    cd $HOME/gcloud && 
    tar xzf google-cloud-sdk.tar.gz && 
    printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh && 
    cd $TRAVIS_BUILD_DIR;
  fi
- if [ -a client_credentials.json ]; then 
    gcloud -q auth activate-service-account --key-file client_credentials.json; 
  fi
install:
- npm install
script:
- npm test
deploy:
- provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh
  skip_cleanup: true
  on:
    branches:
      only:
      - gcp
      - develop