language: python
node_js: 8
python: 3.6
install:
  - npm install
  - pip install awscli
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  - provider: script
    script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh $TRAVIS_COMMIT i-0feb65e210a1d6181 $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh $TRAVIS_COMMIT i-0681121fd2e19ea41 $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch: develop
