language: node_js
node_js: 8
services:
- docker
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_1a9b5f4c6fc9_key -iv $encrypted_1a9b5f4c6fc9_iv -in scripts/client_credentials.json.enc -out scripts/client_credentials.json -d
- curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-280.0.0-linux-x86_64.tar.gz
- tar zxf google-cloud-sdk-280.0.0-linux-x86_64.tar.gz google-cloud-sdk
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- sh google-cloud-sdk/install.sh
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud version
- if [ -a scripts/client_credentials.json ]; then 
    gcloud -q auth activate-service-account --key-file scripts/client_credentials.json;
  fi
install:
- npm install
script:
- npm test
deploy:
- provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(gcp|develop)$