language: python
node_js: 8
python: 3.6
install:
  - npm install
  - pip install awscli
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  - provider: script
    script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh $TRAVIS_COMMIT i-02fd1798f1ce6963a $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch: master
  # - provider: script
  #   script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh $TRAVIS_COMMIT i-028018a7f5b27a704 $TRAVIS_BRANCH
  #   skip_cleanup: true
  #   on:
  #     branch: develop
